### PR TITLE
Fix issue where instance name rotation was faulty

### PR DESCRIPTION
**Pull request by akalipetis**
Previously, if node2 was deleted in a node1, node2, node3 set, the next node creation would fail since it would always try to assign node3 as a name.
Now, the first available name is always assigned.

Signed-off-by: Antonis Kalipetis <akalipetis@gmail.com>

### CODE REVIEW

**Comment by akalipetis** [comment]
Yeah, it does 😄

**Comment by marcosnils** [comment]
Thx for mergibg this Antonia, this is the reason why we rollbacked yesterday :)

**Comment by akalipetis** [comment]
That's great! 🎉🙌

**Comment by marcosnils** [comment]
It's already deployed ;)

**Pull request merged**
