### PR TITLE
Added keyboard shortcut (Cmd+K) to clear terminal

### PR DESCRIPTION
**Pull request by mikesir87**
I'm so use to using a keyboard shortcut to clear the terminal.  Figured as often as I'm using PWD for presentations, it would be nice to have that here as well.  

Currently captures Cmd+K for Macs.  Not sure if there's an equivalent shortcut for Windows-based environments.  This will do Windows+K, which I'm guessing wouldn't be it.

### CODE REVIEW

**Comment by allamand** [comment]
What about ctrl + l ? That don't work on mac ?

Sébastien

**Comment by marcosnils** [comment]
@mikesir87 as @allamand says,  bash default clear shortcut ctrl + l works in PWD. Cmd + K is something that the MacOs terminal uses, not a standard shortcut. I'd prefer to avoid adding platform / terminal emulator specific shortcuts as possible.

@xetorthio ?

**Comment by xetorthio** [comment]
We could have some sort of shortcuts setting for people to choose from. It
seems like shortcuts makes people happy, and we want people happy :)

**Comment by marcosnils** [comment]
In that case I believe the proper way to proceed would be to create a shortcut "presets" feature, where anyone can create a new preset with the defaults for that platform / term emulator. I'd like to avoid just adding random shortcuts all over the place that might become difficult to maintain afterwards.

IMHO this feature won't be really outstanding, after all PWD is just a bash terminal, I don't think there are too many crazy shortcuts we could add, but I could perfectly wrong.

**Comment by xetorthio** [comment]
I guess having a preset for mac and for Linux is already worth it and
should be pretty simple to add.

**Comment by mikesir87** [comment]
Huh... Ctrl + l isn't working for my on my Mac.

But anywho... I'd be happy to work on a shortcut "presets" feature. I already have a data model in mind that should make it pretty easy to implement.  Any recommendations for starting preset names and their shortcuts?  Beyond clearing the screen, I'm not really sure what else might be of value.

As far as UI/UX... do we want a settings cog somewhere in the top-left corner that opens a modal?  For now, could just have the preset option, but there might be more in the future.  Would also give room to show what the keyboard shortcuts actually are.

(And feel free to close this PR and move discussion to an issue if you decide this is worth pursuing)

**Comment by xetorthio** [comment]
Discussion moved to #98

**Pull request closed without merging**
