### PR TITLE
Validates that user is a human.

### PR DESCRIPTION
**Pull request by xetorthio**
Add google recaptcha as an initial page before creating any session.
To configure recaptcha there are 2 environment variables that are needed
`GOOGLE_RECAPTCHA_SITE_KEY` and `GOOGLE_RECAPTCHA_SITE_SECRET`.
The code contains development defaults that should be set in production
to real values.
**NOTICE: Development defaults assume that the domain is `localhost`**

### CODE REVIEW

**Comment by xetorthio** [comment]
Closes #17

**Comment by xetorthio** [comment]
:bell: @marcosnils

**Comment by marcosnils** [comment]
@xetorthio looks ok, let me check in my local env. before merging

**Comment by marcosnils** [comment]
One thing that I don't like is that if I already verified myself as a human, if I try to create another session it will ask again. Is there something we can do to prevent this with a cookie or something?

**Comment by xetorthio** [comment]
Not sure what you would store in a cookie to make sure the user is human.

**Comment by marcosnils** [comment]
Welll.. I'm not sure, but it's better than not having a captcha. LGTM!

**Pull request merged**
