### PR TITLE
Develop on a container

### PR DESCRIPTION
**Pull request by xetorthio**
Adds a Makefile to make the virtual box creation, start and app run reproducible.
This allows to develop PWD on a container, which is nice and also
necessary once "reverse proxy" feature is introduced.

### CODE REVIEW

**Comment by xetorthio** [comment]
:bell: @marcosnils

**Comment by marcosnils** [comment]
@xetorthio have you seen this https://github.com/docker/machine/pull/3798?. I believe it might help to simplify the setup process a lot

**Comment by marcosnils** [comment]
One thing that I don't like is that after makign `make run` if I make a change to the golang code I have to reload the app and I don't have make targets for that. 

It'd be awesome if we can make something that just leaves everything ready so I can do `docker-compose up/stop/restart` from my shell to manage the app instead of using makefile targets. 

Or maybe we can use a tool or something for development that automatically reloads the app if the golang code changes. 

WDYT?

**Comment by xetorthio** [comment]
But that's how go works. You need to recompile and reload if you change
something.

**Comment by marcosnils** [comment]
> But that's how go works. You need to recompile and reload if you change
> something.

yes, but we don't have an easy way or make targets to do that.  I guess the `make run` target confuses things a bit as you're using makefile to run the app but you have to setup compose separately to stop it and restart if you change Go code. 

Maybe we can just remove the `run` target and then add something like this in the README:

- Clone the repo
- Run make
- Make compose use your PWD instance with eval $(docker-compose env pwd)

**Comment by xetorthio** [comment]
OK. Fair enough :)

**Comment by alexellis** [comment]
This looks really useful @xetorthio - is it on hold?

**Comment by xetorthio** [comment]
No. Not on hold. I need to make a small change and then it is ready to
merge :)

**Pull request merged**
