### PR TITLE
Show a server disconnected message

### PR DESCRIPTION
**Pull request by xetorthio**

### CODE REVIEW

**Comment by xetorthio** [comment]
Closes #33

**Comment by xetorthio** [comment]
:bell: @marcosnils

**Comment by marcosnils** [comment]
@xetorthio it's super nice. Maybe a different background color like light yellow or red would be better as the grey kind of confuses with the white background. But it looks amazing!.

**Comment by xetorthio** [comment]
Can you suggest a color code you like?

**Comment by marcosnils** [comment]
#FDF4B6 ?

**Pull request merged**
