### PR TITLE
Allow to specify image new when creating instances

### PR DESCRIPTION
**Pull request by marcosnils**
@xetorthio ping

### CODE REVIEW

**Comment by marcosnils** [comment]
@xetorthio :bell: :snail: :turtle:

**Comment by marcosnils** [comment]
> We never pull de image. So what would be the use case for this? Should we pull the image too?

I don't think so, otherwise people could just make us pull whatever image they want. The idea behind this is to have an explicit available set of "official PWD images" and then allow users to select them through the SDK or via the frontend in PWD. But images won't be pulled on demand, we have to make sure that they exist on the server.

**Comment by xetorthio** [comment]
Understood. Shouldn't we just pull the images and use content trust to only
pull signed images? This way a deployment of a new pwd host would be much
easier and simple.

**Comment by marcosnils** [comment]
> Shouldn't we just pull the images and use content trust to only
> pull signed images? This way a deployment of a new pwd host would be much
> easier and simple.

Sure. We'll have to define the image definition / pulling / verification later.

**Pull request merged**
